name: Build Image
on:
  push:
    branches:
      - main

jobs:
  raspberry-pi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          xargs -a depends sudo apt-get install -y

      - name: Build Image
        run: |
          ./build-docker.sh

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-image
          path: deploy/*.img
